### PR TITLE
Fix monterey detect DND status

### PR DESCRIPTION
**Pull request by nbashkankov**
Hello,
@felixrieseberg @MarshallOfSound 

com.apple.ncprefs approach no longer works for Monterey. 

And actually there could be issue - if you updated to Monterey with DND turned on - ncprefs will still have userPrefs with DND enabled value (MacOS even not erased it on update).

During some investigation i found that there is "~/Library/DoNotDisturb/DB/", which contains all DND setting state. 
It updates immediately after manual/scheduled change of DND status.  So, for Monterey i added logic to read it instead of ncprefs.

Probably its not proper fix, but anyway it works. 
Feel free to provide better solution.

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Thanks for this work! Do you happen to know if this works for older versions, too? I'd hate to break this library on older macOS versions.

**Comment by nbashkankov** [comment]
Package already worked for BigSur and prior versions. My changes just added support for Monterey.
I did check BigSur with Intel - works as before, and Monterey with M1 - also works

**Comment by nbashkankov** [comment]
@felixrieseberg do you still have concerns preventing to merge this?

**Comment by Fiser12** [comment]
I tested it on BigSur and Monterrey. On ARM and on Intel. It was working like a charm.

**Comment by nbashkankov** [comment]
@felixrieseberg @MarshallOfSound - ping - please take a look - can we get this changes released?

**Comment by felixrieseberg** [comment]
Sorry for the delay - and thanks for the email!

**Comment by nbashkankov** [comment]
fixes issue #26

**Comment by hovancik** [comment]
could this be bumped in `electron-notification-state` as well? https://github.com/felixrieseberg/electron-notification-state/issues/7

**Comment by schetle** [comment]
I thought I would add that this does not work in Sandboxed apps, where they do not get direct access to ~/Library.

In a sandboxed app, this results in errors:
`Failed to open °E¯ˇ, error Error Domain=NSCocoaErrorDomain Code=260 "The file “Assertions.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=<PathToLibrary>/Containers/<CFBundleIdentifier>/Data/Library/DoNotDisturb/DB/Assertions.json, NSUnderlyingError=0x600003f67c60 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
`

**Comment by schetle** [comment]
@tboulis It was long enough ago that it's likely changed. You can review the documentation for the INFocusStatusCenter to determine what is required as of today.

**Pull request merged**
